import { Download, FileJson } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { api } from "@/lib/api";
import type { Finding, SeverityLevel } from "@/types";

const SEV_ORDER: SeverityLevel[] = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", "UNKNOWN"];
const SEV_VARIANT: Record<SeverityLevel, "critical" | "high" | "medium" | "low" | "info" | "unknown"> = {
  CRITICAL: "critical",
  HIGH: "high",
  MEDIUM: "medium",
  LOW: "low",
  INFO: "info",
  UNKNOWN: "unknown",
};

interface ExportBarProps {
  scanId: string;
  hasSpdx: boolean;
  selectedColumns: string[];
  findings: Finding[];
  toolName: string;
}

export default function ExportBar({
  scanId,
  hasSpdx,
  selectedColumns,
  findings,
  toolName,
}: ExportBarProps) {
  const severityCounts = SEV_ORDER.reduce<Partial<Record<SeverityLevel, number>>>((acc, s) => {
    const count = findings.filter((f) => f.severity === s).length;
    if (count > 0) acc[s] = count;
    return acc;
  }, {});

  return (
    <TooltipProvider delayDuration={200}>
      <div className="flex flex-wrap items-center gap-3">
        {/* Severity summary badges */}
        <div className="flex items-center gap-1.5 flex-wrap">
          {(Object.entries(severityCounts) as [SeverityLevel, number][]).map(([sev, count]) => (
            <Badge key={sev} variant={SEV_VARIANT[sev]} className="gap-1">
              {sev} {count}
            </Badge>
          ))}
          <span className="text-xs text-muted-foreground font-mono ml-1">
            {findings.length} total
          </span>
        </div>

        <div className="flex-1" />

        {/* Export actions */}
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="outline"
              size="sm"
              className="gap-2"
              onClick={() => {
                window.location.href = api.csvExportUrl(scanId, selectedColumns);
              }}
            >
              <Download className="h-4 w-4" />
              Export CSV
            </Button>
          </TooltipTrigger>
          <TooltipContent className="text-xs">
            Downloads visible columns only. Adjust with the Columns picker.
          </TooltipContent>
        </Tooltip>

        {hasSpdx && (
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="outline"
                size="sm"
                className="gap-2 border-green-300 text-green-700 hover:bg-green-50"
                onClick={() => {
                  window.location.href = api.spdxExportUrl(scanId);
                }}
              >
                <FileJson className="h-4 w-4" />
                Export SPDX
              </Button>
            </TooltipTrigger>
            <TooltipContent className="text-xs max-w-48">
              Downloads the SPDX 2.3 JSON Software Bill of Materials generated by {toolName}.
            </TooltipContent>
          </Tooltip>
        )}
      </div>
    </TooltipProvider>
  );
}
